### ISSUE TITLE
Cross fold issue

### ISSUE THREAD

**Issue by mladencucak** [LudvigOlsen/cvms#10]
I have just checked your post. I might be using your package soon and wanted to give it a go, but...
I have two problems. 
you are missing line where you load the data: 
`data <- participant.scores`   
I suppose this is the data used...? 
```
Also, when I run the 
`data <- fold(data, k = 4, cat_col = 'diagnosis', id_col = 'participant', num_fold_cols = 3)`
Error in fold(data, k = 4, cat_col = "diagnosis", id_col = "participant",  : 
  unused argument (num_fold_cols = 3)
```
It is a fresh instalation...: 
```
> packageVersion("cvms")
[1] ‘0.0.0.9000’
packageVersion("groupdata2")
[1] ‘1.0.0’
```

**Comment by LudvigOlsen** [comment]
Hi @mladencucak! Thanks for your message!

I must have forgotten! I will add that line right away :) 

For now you need to use the github version of groupdata2. I hope to update the CRAN version later this month. I have just added a note in the post about this.

To install, use: devtools::install_github("ludvigolsen/groupdata")

Hope it works, and I'm glad you will be using the package!

 - Ludvig

**Comment by mladencucak** [comment]
Hi @LudvigOlsen 
I did install the github version....

**Comment by mladencucak** [comment]
not sure if this is compatibility issue, just tried on another pc, and: 
`Warning in install.packages :
  package ‘cvms’ is not available (for R version 3.6.0)`

**Comment by LudvigOlsen** [comment]
Hmm. The master branch definitely has the changes, and num_fold_cols are in the package when I install it myself from github. Not sure why it would download the previous version on your machine. Can you force reinstall it?

I'll look into the 3.6.0 version problems for cvms! Thanks for letting me know :)

**Comment by mladencucak** [comment]
This "inspired" me to update R&Rstudio, reinstalled your packages and it works now.

**Comment by LudvigOlsen** [comment]
That's great to hear! :)

**Comment by mladencucak** [comment]
👍🙃

**Comment by LudvigOlsen** [comment]
Btw., do let me know if you have any suggestions for additions or improvements when you use the package. It can be hard to predict all use cases :)

**Comment by mladencucak** [comment]
Sure! Well, I work with plant diseases and am a wannabe data analyst. :) 
This is my first piece of work where I have evaluated an old empirical model for risk prediction. 
[https://mladencucak.github.io/AnalysisPLBIreland/](url)
I am working on something a bit more sophisticated at the moment and would like to use something fancy for evaluation of the new model based on some 150 disease outbreaks over 10 years.

**Comment by LudvigOlsen** [comment]
Looks like a pretty project! Irish Rules is a fun name :p
