### ISSUE TITLE
Simpler layout for confusion matrix plots

### ISSUE THREAD

**Issue by xgirouxb** [LudvigOlsen/cvms#12]
First off, this is a great package and thanks for all the work!

I'd like to pitch a feature request for the `plot_confusion_matrix()` function. As it is currently implemented it is only possible to add row and column percentages to every tile. While in some instances it may be useful to have these metrics for each tile, it does leave quite a bit of clutter. I suspect for most people, restricting the row and column percentages to be disaplyed only in the diagonal tiles would provide the most essential information: errors of omission/commission for each class (or rather 100% - errors).

**Comment by LudvigOlsen** [comment]
Hi Xavier @xgirouxb ,

This seems like a useful addition, so I'll put it on my list. 
Do you need it for a project right now?

> First off, this is a great package and thanks for all the work!

Thanks! :)

**Comment by xgirouxb** [comment]
Thanks @LudvigOlsen ! No rush, I usually use inkscape for all my final plot edits and enhancements so its easy to remove extra data in that step

**Comment by LudvigOlsen** [comment]
Cool! 
I've implemented the feature although it might be a while before it becomes available.

Do write if you find more potential improvements :)

**Comment by LudvigOlsen** [comment]
@xgirouxb 
This was added in the recent update. See the `diag_percentages_only` argument.
