### ISSUE TITLE
Feature request: column and row sums in plot_confusion_matrix

### ISSUE THREAD

**Issue by MaraAlexeev** [LudvigOlsen/cvms#15]
For `plot_confusion_matrix()` it would be useful to have additional sums/% feature available in the plot function as below.

![image](https://user-images.githubusercontent.com/39673697/96358288-86c2f680-10d3-11eb-872a-6283c0ab7f6d.png)

**Comment by LudvigOlsen** [comment]
I did actually consider this previously but never got around to it. 
It would probably be a horizontal bar underneath and a vertical bar to the right with the counts and percentages. 

Something similar to this:

![image](https://user-images.githubusercontent.com/22819047/96362816-49d91d00-1130-11eb-8c88-f9348e3c4c9f.png)
from https://github.com/wcipriano/pretty-print-confusion-matrix

I would probably just have a single percentage though, as the row/col percentages already give the information that the two percentages in this plot gives.

**Comment by LudvigOlsen** [comment]
@MaraAlexeev 
I've been playing around with this for a couple of hours now and this is what I've got so far:

<img width="457" alt="Screen Shot 2020-10-18 at 16 23 26" src="https://user-images.githubusercontent.com/22819047/96370522-65f3b300-115e-11eb-9e08-79af04507bfe.png">

Still have a lot of work to do on it, but this is the kind of design I'm thinking. What do you think?

**Comment by MaraAlexeev** [comment]
This looks great.

**Comment by LudvigOlsen** [comment]
I merged the functionality to the master branch, so you can try it out.
There's a new `add_sums` argument to enable. The appearance of the sum tiles can be changed in the `sums_settings` argument, using the `sum_tile_settings()` function.

Install with:
`devtools::install_github("LudvigOlsen/cvms")`
