### ISSUE TITLE
Grid search? 

### ISSUE THREAD

**Issue by Rysias** [LudvigOlsen/cvms#16]
In the (awesome) readme it says something about grid search, but I cannot find a function to do so. Is it something you have to implement yourself, or is there some nifty trick I have overlooked? :)) 

Btw, totally loving the package - especially how well it works with repeated measures 👍

**Comment by LudvigOlsen** [comment]
Hi @Rysias,

In `cross_validate_fn()` you can enable grid search by supplying lists of values to try combinations of.

There's an example here:
http://ludvigolsen.dk/cvms/cross_validate_custom_model_function/#specifying-hyperparameters-for-grid-search

Thanks for the nice comment :)

**Comment by Rysias** [comment]
Just what I was looking for! Thanks a bunch :))
