### ISSUE TITLE
Name correction

### ISSUE THREAD

**Issue by arcuo** [LudvigOlsen/cvms#22]
Change name to "Hugh Benjamin" from "Benjamin Hugh" in DESCRIPTION

**Comment by LudvigOlsen** [comment]
I think this is asking a bit much. I will consider it for a few months and get back to you! ;)
Alternatively, changing your name still seems like an easier solution to this bug!

**Comment by LudvigOlsen** [comment]
Dear Hugh Benjamin Hugh Zachariae @arcuo,
It is my immense pleasure to officially announce your name change. 
Congratulations and may you live happily ever after.

Best,
Best roommate

**Comment by arcuo** [comment]
Thank you very much, much appreciated, happy to be here, cool.

Regards,
Regarding roommate
