### ISSUE TITLE
Grand total is empty when add_normalized is set to FALSE

### ISSUE THREAD

**Issue by JianWang2016** [LudvigOlsen/cvms#36]
Dear @LudvigOlsen,

Grand total is disabled when add_normalized = FALSE.  I think Grand total should still be display because add_normalized is about percentage, not count.  Making sense?

Here is an example:

`
# Create targets and predictions data frame
data <- data.frame(
  "target" = c("A", "B", "A", "B", "A", "B", "A", "B",
               "A", "B", "A", "B", "A", "B", "A", "A"),
  "prediction" = c("B", "B", "A", "A", "A", "B", "B", "B",
                   "B", "B", "A", "B", "A", "A", "A", "A"),
  stringsAsFactors = FALSE
)

# Evaluate predictions and create confusion matrix
eval <- evaluate(
  data = data,
  target_col = "target",
  prediction_cols = "prediction",
  type = "binomial"
)

eval

# Or plot first confusion matrix in evaluate() output
plot_confusion_matrix(eval, 
                      add_normalized = FALSE,
                      add_sums = TRUE)

`

**Comment by LudvigOlsen** [comment]
Nice catch, @JianWang2016 ! It was a bug indeed :-)

I've fixed it on the GitHub version. CRAN upload might be a while!

Thanks!

**Comment by JianWang2016** [comment]
thanks very much @LudvigOlsen
