### ISSUE TITLE
support "rectangular" or "asymmetrical" confusion matrices

### ISSUE THREAD

**Issue by omadios** [LudvigOlsen/cvms#37]
Hi,

I love the package, I was wondering if you have any suggestions on how to plot a confusion matrix that is asymmetrical. 

Imagine a case in which I have more targets than predictions (4x3), currently, the figure plotted will be 4x4 but with one row greyed out.

![test](https://github.com/LudvigOlsen/cvms/assets/52498261/a52f6bb0-f5e5-47a7-81d1-834e51efdfe6)

Instead, would like to see that the model predictions are for the out-of-distribution class (the 4th target). Is this possible?

In my mind,

 the easiest way would be to plot the actual 4x3 matrix (with the 4th class missing from the columns but present in the rows)

thank you

**Comment by omadios** [comment]
Excellent, thank you for the prompt reply!

**Comment by jwang-lilly** [comment]
@LudvigOlsen, when filtering as used in the example above, add_sums = TRUE and diag_percentages_only = TRUE would produce error.  Any insight?

**Comment by LudvigOlsen** [comment]
@jwang-lilly Thanks for reporting. I get an error as well and will look into it.

**Comment by jwang-lilly** [comment]
@LudvigOlsen, thanks much for looking into this.

**Comment by LudvigOlsen** [comment]
@jwang-lilly I figured out the error. The current master branch version should work. I'll get it on CRAN sometime this week!

**Comment by LudvigOlsen** [comment]
@jwang-lilly Fix is now on CRAN!
