### ISSUE TITLE
From scientific to common notation in output

### ISSUE THREAD

**Issue by fusaroli** [LudvigOlsen/cvms#4]
Currently the function produces an output in scientific notation (e.g. 1.466119e-02). It would be less intimidating to produce it in common notation (e.g. 0.01466119).

**Comment by LudvigOlsen** [comment]
Yay! My first issue!   
You're right. That would be better. Will put it on my list!

**Comment by LudvigOlsen** [comment]
Can't reproduce it. Let me know if it still happens with the new tibble output? Closing topic for now.
