### ISSUE TITLE
Cleaning up the binomial output

### ISSUE THREAD

**Issue by fusaroli** [LudvigOlsen/cvms#5]
CI2 is confusing. Can you remove it and report lower CI and upper CI (instead of CI1 and CI2).
Precision and recall could be removed, so to avoid duplicates. Then the manual could explain that.

A possible robust balanced accuracy estimation, which accounts for random effects is this: http://people.inf.ethz.ch/bkay/downloads/Readme_micp_for_R.pdf

**Comment by LudvigOlsen** [comment]
Yeah, CI2 is just the AUC. 
I will look into the accuracy estimation! :) (Probably in a months time when the exams are done, but keep the great suggestions coming :) )

**Comment by LudvigOlsen** [comment]
The micp paper is gone. Closing topic! 👯

**Comment by fusaroli** [comment]
https://kaybrodersen.github.io/downloads/Readme_micp_for_R.pdf :-P

**Comment by LudvigOlsen** [comment]
Not on CRAN unfortunately :(
